### ISSUE TITLE
Is unlearned model weights available?

### ISSUE THREAD

**Issue by zjysteven** [yaojin17/Unlearning_LLM#3]
Hi,

I'm interested to perform some downstream tasks on unlearned models. Will the unlearned model weights be released?

Thanks

**Comment by yaojin17** [comment]
Thanks for your interest in our work! Our full code is released. Since our methods don't require too much computational resources, we don't have a plan to release the unlearned model weights. I do have a backup of the unlearned model weights for the main experiment, if you have a special need for those model's weights, I could send it to you.

**Comment by tbozhong** [comment]
Hi there,
Thanks for your great work to community! 
Can you send these models' checkpoints to me? My email is `tbozhong@zju.edu.cn`, looking forward to your reply!

**Comment by yaojin17** [comment]
Hello @tbozhong. The total storage of all checkpoints is about 238GB. It is difficult to download those from a remote server and upload them to one cloud storage system. Could you specify which checkpoints you need? Then I could upload them to OneDrive manually and share them with you.

**Comment by tbozhong** [comment]
Thanks for your reply!

Could you upload the checkpoints according to `cais/Zephyr_RMU` to Hugging Face? It will be convenient for us.
Thank you for considering this request!
